In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 6, 4, 5])

flipped = np.flip(arr)

print(flipped)

[5 4 6 3 2 1]


In [ ]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
res = np.ndarray.flatten(array1)
print(res)

[1 2 3 2 4 5 1 2 3]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [4, 4]])

comparison = arr1 == arr2
equal_arrays = comparison.all()

print(equal_arrays)

False


In [ ]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
x_count = np.bincount(x)
x_most_frequent = np.argmax(x_count)
x_indices = np.where(x == x_most_frequent)[0]
print(x_most_frequent, x_indices)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
y_counts = np.bincount(y)
y_most_frequent = np.argmax(y_counts)
y_indices = np.where(y == y_most_frequent)[0]
print(y_most_frequent, y_indices)

1 [0 5 7 8 9]
1 [0 1 2]


In [ ]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(np.matrix.sum(gfg))
print(np.matrix.sum(gfg,axis = 1))
print(np.matrix.sum(gfg,axis = 0))

45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [ ]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print(np.matrix.diagonal(n_array).sum(),end="\n\n")
print(np.linalg.eig(n_array).eigenvalues,end="\n\n")
print(np.linalg.eig(n_array).eigenvectors, end="\n\n")
print(np.linalg.inv(n_array),end="\n\n")
print(np.linalg.det(n_array))

176

[98.16835147 28.097044   49.73460452]

[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]

[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]

137180.0000000001


In [ ]:
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
print(np.dot(p,q),end="\n\n")
print(np.cov(p,q))

[[16 19]
 [26 31]]

[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [ ]:
p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]
print(np.dot(p,q),end="\n\n")
print(np.cov(np.ravel(p),np.ravel(q)))

[[16 19  5]
 [26 31  8]
 [46 55 14]]

[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [ ]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(y,x))

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[ 20  -4  -7]
 [ 84 -36 -20]]


In [ ]:
array = np.array([[1, -2, 3],[-4, 5, -6]])
print(np.abs(array),end = "\n\n")
arr = array.flatten()

print(np.percentile(arr,25))
print(np.percentile(arr,50))
print(np.percentile(arr,75),end="\n\n")

print(arr.mean())
print(np.median(arr))
print(np.std(arr))

[[1 2 3]
 [4 5 6]]

-3.5
-0.5
2.5

-0.5
-0.5
3.8622100754188224


In [ ]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])

print(np.floor(a), np.ceil(a), np.trunc(a), np.round(a))

[-2. -2. -1.  0.  1.  1.  3.] [-1. -1. -0.  1.  2.  2.  3.] [-1. -1. -0.  0.  1.  1.  3.] [-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

sorted_array = np.sort(array)
indices_sorted_array = np.argsort(array)
four_smallest_elements = np.sort(array)[:4]
five_largest_elements = np.sort(array)[-5:]

print(sorted_array, indices_sorted_array, four_smallest_elements, five_largest_elements, sep= "\n")

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]


In [ ]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

integer_elements = array[array == array.astype(int)]

float_elements = array[array != array.astype(int)]

print(integer_elements, float_elements,sep="\n")

[1. 2. 3. 2.]
[1.2 2.2]


In [ ]:
from PIL import Image
import numpy as np

In [ ]:
text_file_path=""
def img_to_array(path):
    global text_file_path
    with Image.open(path) as img:
        img_array = np.array(img)
        if len(img_array.shape) == 3:
            img_type = 'RGB'
        elif len(img_array.shape) == 2:
            img_type = 'Grayscale'
        else:
            raise ValueError("Unsupported image format")

        img_array_text = np.array2string(img_array, separator=',', threshold=np.inf)

        text_file_path = path.rsplit('.', 1)[0] + '_array.txt'
        with open(text_file_path, 'w') as file:
            file.write(f"Image Type: {img_type}\n")
            file.write("Array Data:\n")
            file.write(img_array_text)

        print(f"Image array saved to {text_file_path}")

In [ ]:
img_to_array('upload.png')

Image array saved to upload_array.txt


In [ ]:

with open(text_file_path, 'r') as file:
    file_content = file.read()
    print(file_content)